### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by gingerbeardman** [13xforever/cwcheat-sublime-syntax#1]
I know how to do it manually, but it would be good to include an easy way to install (via package control) or at least manual steps in the readme

Thanks for this useful syntax!

**Comment by 13xforever** [comment]
you can always add the github url as a package repository 
![image](https://user-images.githubusercontent.com/36445/54556712-48d38d00-49db-11e9-8491-32ba20d416e6.png)

**Comment by gingerbeardman** [comment]
Cool I was not aware of that method!
